In [ ]:
# Numpy

In [ ]:
pip install numpy


In [4]:
import numpy as np
import pandas as pd

In [8]:
prime_array=np.array((2,3,5,7,11))
print(prime_array)

[ 2  3  5  7 11]


In [11]:
#2D array
prime_array=np.array([[2,3,5,7,11],[13,17,19,23,29]])
print(prime_array)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


In [14]:
#3D array
array=np.array([[[2,3,5],[7,11,13],[13,17,19],[23,25,29]],[[2,3,5],[7,11,13],[13,17,19],[23,25,29]]])
print(array)

[[[ 2  3  5]
  [ 7 11 13]
  [13 17 19]
  [23 25 29]]

 [[ 2  3  5]
  [ 7 11 13]
  [13 17 19]
  [23 25 29]]]


In [ ]:
#Why numpy?
Numpy data stuctures perform better in :
1.memory: Numpy data structures take up less space
2.performance: they  have a need for speed and are faster than lists
3.functionality: sciPy and numPyhave optimized functions such as linear algebra operations and built-in.

In [8]:
import numpy as np
a1=np.ones(6)
a1
# a2=np.zeros(5)
# a2

array([1., 1., 1., 1., 1., 1.])

In [15]:
Arravali=np.array(np.random.randint(1,10,(3,3)))
print("the defined array is \n(Arravali)")
print(Arravali)

the defined array is 
(Arravali)
[[8 5 8]
 [3 8 6]
 [8 8 3]]


In [6]:
print(np.transpose(Arravali))

[[31 43 23 26 11 27 36 44]
 [26 24 43 43 15 44 20 37]]


In [8]:
print(np.reshape(Arravali,(4,4)))

[[31 26 43 24]
 [23 43 26 43]
 [11 15 27 44]
 [36 20 44 37]]


In [9]:
Arravali=np.array(np.random.randint(10,45,(8,2,4)))
print("the defined array is \n(Arravali)")
print(Arravali)

the defined array is 
(Arravali)
[[[24 14 42 20]
  [13 30 26 27]]

 [[31 24 27 30]
  [25 30 12 42]]

 [[22 17 38 38]
  [14 26 35 39]]

 [[35 17 28 39]
  [37 21 11 44]]

 [[27 27 17 13]
  [34 32 33 35]]

 [[18 24 19 13]
  [13 23 11 21]]

 [[24 22 17 12]
  [37 39 18 14]]

 [[40 21 12 20]
  [38 35 35 25]]]


In [11]:
print(np.resize(Arravali,(4,3)))


[[24 14 42]
 [20 13 30]
 [26 27 31]
 [24 27 30]]


In [28]:
a=np.random.randint(10,20,(3,2,4))
print(a)
print(a.shape)

[[[10 17 17 10]
  [10 17 18 12]]

 [[18 16 16 14]
  [13 11 15 10]]

 [[13 14 18 19]
  [16 11 12 10]]]
(3, 2, 4)


In [15]:
np.insert(a,0,100,axis=0)

array([[[100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 17,  19,  17,  18],
        [ 16,  12,  17,  11]],

       [[ 11,  19,  13,  12],
        [ 15,  19,  15,  12]],

       [[ 16,  10,  13,  16],
        [ 11,  17,  16,  16]]])

In [30]:
a=np.random.randint(2,9,(2,3,4))
b=np.random.randint(10,20,(2,3,4))
c=np.append(a,b,axis=0)
print(c)
# np.append(a,20)

[[[ 5  3  3  4]
  [ 6  7  2  8]
  [ 6  4  6  5]]

 [[ 3  7  8  3]
  [ 8  7  6  4]
  [ 3  6  8  4]]

 [[13 10 13 18]
  [11 11 13 12]
  [16 19 18 18]]

 [[14 13 19 10]
  [17 19 16 14]
  [10 17 15 17]]]
